// Generated by gencpp from file uv_robot_ros/cmdToRpi.msg
// DO NOT EDIT!


#ifndef UV_ROBOT_ROS_MESSAGE_CMDTORPI_H
#define UV_ROBOT_ROS_MESSAGE_CMDTORPI_H

#include <ros/service_traits.h>


#include <uv_robot_ros/cmdToRpiRequest.h>
#include <uv_robot_ros/cmdToRpiResponse.h>


namespace uv_robot_ros
{

struct cmdToRpi
{

typedef cmdToRpiRequest Request;
typedef cmdToRpiResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct cmdToRpi
} // namespace uv_robot_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uv_robot_ros::cmdToRpi > {
  static const char* value()
  {
    return "4b2b21c7747f71f43af6626178a5bf39";
  }

  static const char* value(const ::uv_robot_ros::cmdToRpi&) { return value(); }
};

template<>
struct DataType< ::uv_robot_ros::cmdToRpi > {
  static const char* value()
  {
    return "uv_robot_ros/cmdToRpi";
  }

  static const char* value(const ::uv_robot_ros::cmdToRpi&) { return value(); }
};


// service_traits::MD5Sum< ::uv_robot_ros::cmdToRpiRequest> should match
// service_traits::MD5Sum< ::uv_robot_ros::cmdToRpi >
template<>
struct MD5Sum< ::uv_robot_ros::cmdToRpiRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uv_robot_ros::cmdToRpi >::value();
  }
  static const char* value(const ::uv_robot_ros::cmdToRpiRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uv_robot_ros::cmdToRpiRequest> should match
// service_traits::DataType< ::uv_robot_ros::cmdToRpi >
template<>
struct DataType< ::uv_robot_ros::cmdToRpiRequest>
{
  static const char* value()
  {
    return DataType< ::uv_robot_ros::cmdToRpi >::value();
  }
  static const char* value(const ::uv_robot_ros::cmdToRpiRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uv_robot_ros::cmdToRpiResponse> should match
// service_traits::MD5Sum< ::uv_robot_ros::cmdToRpi >
template<>
struct MD5Sum< ::uv_robot_ros::cmdToRpiResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uv_robot_ros::cmdToRpi >::value();
  }
  static const char* value(const ::uv_robot_ros::cmdToRpiResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uv_robot_ros::cmdToRpiResponse> should match
// service_traits::DataType< ::uv_robot_ros::cmdToRpi >
template<>
struct DataType< ::uv_robot_ros::cmdToRpiResponse>
{
  static const char* value()
  {
    return DataType< ::uv_robot_ros::cmdToRpi >::value();
  }
  static const char* value(const ::uv_robot_ros::cmdToRpiResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UV_ROBOT_ROS_MESSAGE_CMDTORPI_H
