// Generated by gencpp from file practice/my_srv.msg
// DO NOT EDIT!


#ifndef PRACTICE_MESSAGE_MY_SRV_H
#define PRACTICE_MESSAGE_MY_SRV_H

#include <ros/service_traits.h>


#include <practice/my_srvRequest.h>
#include <practice/my_srvResponse.h>


namespace practice
{

struct my_srv
{

typedef my_srvRequest Request;
typedef my_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct my_srv
} // namespace practice


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::practice::my_srv > {
  static const char* value()
  {
    return "b8a2aab5099fa54e0eb1247d552c20ed";
  }

  static const char* value(const ::practice::my_srv&) { return value(); }
};

template<>
struct DataType< ::practice::my_srv > {
  static const char* value()
  {
    return "practice/my_srv";
  }

  static const char* value(const ::practice::my_srv&) { return value(); }
};


// service_traits::MD5Sum< ::practice::my_srvRequest> should match
// service_traits::MD5Sum< ::practice::my_srv >
template<>
struct MD5Sum< ::practice::my_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::practice::my_srv >::value();
  }
  static const char* value(const ::practice::my_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::practice::my_srvRequest> should match
// service_traits::DataType< ::practice::my_srv >
template<>
struct DataType< ::practice::my_srvRequest>
{
  static const char* value()
  {
    return DataType< ::practice::my_srv >::value();
  }
  static const char* value(const ::practice::my_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::practice::my_srvResponse> should match
// service_traits::MD5Sum< ::practice::my_srv >
template<>
struct MD5Sum< ::practice::my_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::practice::my_srv >::value();
  }
  static const char* value(const ::practice::my_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::practice::my_srvResponse> should match
// service_traits::DataType< ::practice::my_srv >
template<>
struct DataType< ::practice::my_srvResponse>
{
  static const char* value()
  {
    return DataType< ::practice::my_srv >::value();
  }
  static const char* value(const ::practice::my_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PRACTICE_MESSAGE_MY_SRV_H
